In [1]:
import cv2
import numpy as np

# Cargar una imagen desde el archivo
imagen = cv2.imread('imagen.jpg')

# Verifica si la imagen se ha cargado correctamente
if imagen is not None:
    # Convierte la imagen en una matriz NumPy
    matriz = np.array(imagen)
    
    # Ahora puedes trabajar con la matriz de la imagen
    print("Matriz de la imagen:")
    print(matriz)
else:
    print("No se pudo cargar la imagen.")


Matriz de la imagen:
[[[34 27  8]
  [34 27  8]
  [34 27  8]
  ...
  [29 20  6]
  [29 20  6]
  [29 20  6]]

 [[34 27  8]
  [34 27  8]
  [34 27  8]
  ...
  [29 20  6]
  [29 20  6]
  [29 20  6]]

 [[34 27  8]
  [34 27  8]
  [34 27  8]
  ...
  [29 20  6]
  [29 20  6]
  [29 20  6]]

 ...

 [[19 15  4]
  [15 11  0]
  [11  7  0]
  ...
  [31 25  6]
  [32 26  7]
  [33 27  8]]

 [[17 13  2]
  [13  9  0]
  [20 16  5]
  ...
  [32 26  7]
  [32 26  7]
  [32 26  7]]

 [[17 13  2]
  [13  9  0]
  [20 16  5]
  ...
  [32 26  7]
  [32 26  7]
  [32 26  7]]]


In [ ]:
cv2.imwrite('matriz_como_imagen.png', matriz)
cv2.imshow('Mi Imagen', matriz)
cv2.waitKey(0)
cv2.destroyAllWindows()